# Generated by Django 5.0.3 on 2024-04-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Product',
        ),
    ]
