# Generated by Django 5.0.3 on 2024-03-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USERS', 'Users'), ('DEALER', 'Dealer')], max_length=50),
        ),
    ]
