# Generated by Django 5.0.3 on 2024-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
