# Generated by Django 5.0.3 on 2024-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer')], default='user', max_length=20),
        ),
    ]
