# Generated by Django 5.0.3 on 2024-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.AddField(
            model_name='user',
            name='dealer_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USERS', 'Users'), ('DEALER', 'Dealer')], default='USERS', max_length=50),
        ),
    ]
