# Generated by Django 5.0.3 on 2024-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0002_alter_user_dealer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dealer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('users', 'Users'), ('dealer', 'Dealer')], default='users', max_length=20),
        ),
    ]
