# Generated by Django 5.0.3 on 2024-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
