# Generated by Django 5.0.3 on 2024-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentialsapp', '0005_product_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('users', 'Users'), ('dealer', 'Dealer')], default='users', max_length=20),
        ),
    ]
